<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>MedAI - temporal dataset</title>
    <!-- Bootstrap 5 -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
            crossorigin="anonymous"></script>
    <!-- jQuery -->
    <link rel="stylesheet" href="//code.jquery.com/ui/1.13.2/themes/base/jquery-ui.css">

    <script src="https://code.jquery.com/jquery-3.6.0.js"></script>
    <script src="https://code.jquery.com/ui/1.13.2/jquery-ui.js"></script>
    <script src="/js/medai.js"></script>

</head>

<body>
<?php
$now = new \DateTime();
$startTime = clone($now);
$startTime->sub(new \DateInterval('P7D'));
$queryType = $params['query_type']??'history';
$importMode = $params['import_mode'] ?? 'clean';
?>
<div class="container mt-3 border rounded bg-light bg-gradient mt-2 p-3">
    <form id="upload-form" action="/upload" method="POST" enctype="multipart/form-data">
        <div class="row">
            <h5> Upload File:</h5>
            <div class="col-md-4">
                <select class="form-select" aria-label="Default select example" name="import_mode" id="import_mode">
                    <option value="clean" <?= ($importMode == 'clean' ? 'selected=selected' :'');?>>Clean (Erase old data)</option>
                    <option value="additive" <?= ($importMode == 'additive' ? 'selected=selected' :'');?>>Import only new Records</option>
                </select>
            </div>
            <div class="col-md-5">

                <input type="file" name="filename" class="form-control"
                       accept="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet, application/vnd.ms-excel">
            </div>
            <div class="col-md-2">
                <button type="submit" class="btn btn-secondary">Upload</button>

            </div>
        </div>

    </form>
</div>

<div class="container mt-3 border rounded bg-light bg-gradient mt-2 p-3">

    <form id="search-form">
        <h5> Search:</h5>
        <div class="row mb-3">
            <div class="col-md-2">
                <label for="pov_date" class="form-label">Point of View:</label>
                <input type="date" name="pov_date" value="<?= htmlentities($params['pov_date'] ?? null); ?>"
                       class="form-control">

            </div>
            <div class="col-md-2">
                <label for="pov_hour" class="form-label">&nbsp;</label>
                <input type="time" name="pov_hour" value="<?= htmlentities($params['pov_hour'] ?? '23:59'); ?>"
                       class="form-control">
            </div>

            <div class="col-md-4">
                <label for="client" class="form-label">Client:</label>
                <input id="client" class="form-control autocomplete"
                       placeholder="type to search..." name="client"
                       value="<?= htmlentities($params['client'] ?? ''); ?>"/>
                <input type="hidden" id="client_id" name="client_id"
                       value="<?= htmlentities($params['client_id'] ?? ''); ?>"/>

            </div>
            <div class="col-md-4">
                <label for="loinc" class="form-label">LOINC Code:</label>
                <input id="loinc" class=" form-control autocomplete" name="loinc"
                       value="<?= htmlentities($params['loinc'] ?? ''); ?>" placeholder="type to search..."/>
                <input type="hidden" id="loinc_id" name="loinc_id"
                       value="<?= htmlentities($params['loinc_id'] ?? ''); ?>"/>

            </div>

        </div>
        <div class="row mb-3">
            <div class="col-md-4">
                <label for="from_date" class="form-label">Query Type:</label>
                <select class="form-select" aria-label="Default select example" name="query_type" id="query_type">
                    <option value="retrieval" <?= ($queryType == 'retrieval' ? 'selected=selected' :'');?>>Retrieval</option>
                    <option value="history" <?= ($queryType == 'history' ? 'selected=selected' :'');?>>History</option>
                </select>
            </div>

            <div class="history-section section-modifier col-md-2">
                <label for="from_date" class="form-label">From:</label>
                <input type="date" name="from_date" value="<?= htmlentities($params['from_date'] ?? null); ?>"
                       class="form-control">
            </div>
            <div class="history-section section-modifier  col-md-2">
                <label for="from_hour" class="form-label">&nbsp;</label>
                <input type="time" name="from_hour" value="<?= htmlentities($params['from_hour'] ?? '00:00'); ?>"
                       class="form-control">
            </div>

            <div class="history-section section-modifier col-md-2">
                <label for="to_date" class="form-label">To</label>
                <input type="date" name="to_date" value="<?= htmlentities($params['to_date'] ?? null); ?>"
                       class="form-control">
            </div>
            <div class="history-section section-modifier  col-md-2">
                <label for="to_hour" class="form-label">&nbsp;</label>
                <input type="time" name="to_hour" value="<?= htmlentities($params['to_hour'] ?? '23:59'); ?>"
                       class="form-control">
            </div>

            <div class="retrieval-section section-modifier col-md-2">
                <label for="at_date " class="form-label">At</label>
                <input type="date" name="at_date" value="<?= htmlentities($params['at_date'] ?? null); ?>"
                       class="form-control"/>
            </div>
            <div class="retrieval-section  section-modifier col-md-2">
                <label for="at_hour" class="form-label">&nbsp;</label>
                <input type="time" name="at_hour" value="<?= htmlentities($params['at_hour'] ?? null); ?>"
                       class="form-control"/>
            </div>


        </div>


<div class="row mb-3">

    <div class="col mb-12 text-center">
        <button id="reset" type="reset" class="btn btn-warning">Reset</button>
        <button type="submit" class="btn btn-secondary">Search</button>
    </div>

</div>
</form>
</div>


<div class="container mt-3">
    <table class="table table-striped sortable" id="results-table">
        <thead>
        <tr>
            <th nowrap="nowrap">ID</th>
            <th nowrap="nowrap">First Name</th>
            <th nowrap="nowrap">Last Name</th>
            <th nowrap="nowrap">Concept Name</th>
            <th nowrap="nowrap">LOINC CODE</th>
            <th nowrap="nowrap">Value</th>
            <th nowrap="nowrap">Valid Start Time</th>
            <th nowrap="nowrap">Valid Stop Time</th>
            <th nowrap="nowrap">Transaction Time</th>
            <th>
                <button type="button" id="addBtn" class="btn btn-secondary" data-toggle="modal"
                        data-target="#recordModal">Add
                </button>
            </th>
        </tr>
        </thead>
        <tbody>
        <?php if (empty($results)) { ?>
            <tr>
                <td colspan="10"> No results found</td>
            </tr>
        <?php } else {
            foreach ($results as $row) {
                ?>
                <tr>
                    <td><?= $row->id; ?></td>
                    <td><?= htmlentities($row->first_name); ?></td>
                    <td><?= htmlentities($row->last_name); ?></td>
                    <td><?= htmlentities($row->loinc_long_common_name); ?></td>
                    <td><?= htmlentities($row->loinc_code); ?></td>
                    <td nowrap="nowrap"><?= htmlentities($row->value . ' ' . $row->unit); ?></td>

                    <td nowrap="nowrap"><?= humanTime($row->valid_start_time); ?></td>
                    <td nowrap="nowrap"><?= humanTime($row->valid_end_time); ?></td>
                    <td nowrap="nowrap"><?= humanTime($row->transaction_time); ?></td>
                    <td nowrap="nowrap">


                        <?php if ($row->is_deleted) {
                            ?>
                            <span title="this record was deleted on <?= humanTime($row->deleted_at); ?>">&#x26A0;</span>
                        <?php } else { ?>
                            <a href="#" class="editBtn text-decoration-none text-success"
                               data-id="<?= $row->id; ?>"><span title='Edit'
                                                                style='font-size:20px;'>&#9998;</span></a> &nbsp;
                            <a href="#" class="deleteBtn text-decoration-none text-danger"
                               data-id="<?= $row->id; ?>"><span title='Delete' style='font-size:20px;'>&#128473;</span></a>
                        <?php } ?>
                    </td>
                </tr>
            <?php }
        } ?>
        </tbody>

    </table>
</div>


<div class="container mt-3 border rounded bg-light bg-gradient mt-2 p-3">

    <pre><?= htmlentities($qry) ?? ''; ?></pre>
</div>


<!-- Modal -->
<div class="modal fade" id="recordModal" tabindex="-1" role="dialog" aria-labelledby="editUpdateModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <form id="recordForm">
                <div class="modal-header">
                    <h4 class="modal-title" id="editUpdateModalLabel">Add/Update</h4>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <input type="hidden" class="form-control" id="clientId" name="client_id">


                    <div class="form-group mb-3 ">
                        <label for="firstName">First Name:</label>
                        <input type="text" class="form-control" id="firstName" name="first_name" required>
                    </div>
                    <div class="form-group mb-3">
                        <label for="lastName">Last Name:</label>
                        <input type="text" class="form-control" id="lastName" name="last_name" required>
                    </div>
                    <div class="form-group mb-3">
                        <label for="loincCode">LOINC CODE:</label>
                        <input type="text" class="form-control" id="loincCode" name="loinc_code" required>
                    </div>
                    <div class="form-group mb-3">
                        <label for="value">Value:</label>
                        <input type="number" step="0.0001" class="form-control" id="value" name="value" required>
                    </div>

                    <div class="form-group mb-3">
                        <label for="unit">Unit:</label>
                        <input type="text" class="form-control" id="unit" name="unit" required>
                    </div>
                    <div class="form-group mb-3">
                        <label for="validStartTime">Valid Start Time:</label>
                        <input type="datetime-local" class="form-control" id="validStartTime" name="valid_start_time"
                               required>
                    </div>
                    <div class="form-group mb-3">
                        <label for="validStopTime">Valid Stop Time:</label>
                        <input type="datetime-local" class="form-control" id="validStopTime" name="valid_stop_time"
                               required>
                    </div>
                    <div class="form-group mb-3">
                        <label for="transactionTime">Transaction Time:</label>
                        <input type="datetime-local" class="form-control" id="transactionTime" name="transaction_time"
                               required>
                    </div>
                </div>
                <div class="modal-footer mb-3">
                    <button type="button" class="btn btn-secondary close" data-dismiss="modal">Close</button>
                    <button type="button" class="save-btn btn btn-primary">Save changes</button>
                </div>
            </form>
        </div>
    </div>
</div>


<div class="modal fade" id="confirmModal" tabindex="-1" role="dialog" aria-labelledby="confirmModalLabel"
     aria-hidden="true">

    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="confirmModalLabel">Confirmation</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <p>Do you want really want to cancel this transaction?</p>
                <em id="recordInfo"></em>
                <form id="deleteForm">
                    <input type="hidden" id="delFirstName" name="first_name"/>
                    <input type="hidden" id="delLastName" name="last_name"/>
                    <input type="hidden" id="delLoincCode" name="loinc_code"/>
                    <input type="hidden" id="delValidStartTime" name="valid_start_time"/>
                    Cancellation time: <input type="datetime-local" id="delDeletedAt" name="deleted_at"/>
                </form>

            </div>
            <div class="modal-footer text-center">
                <input type="hidden" id="delete-id">
                <button type="button" class="close btn btn-secondary" data-dismiss="modal">No, Keep Transaction</button>
                <button type="button" id="deleteSubmit" class="btn btn-danger">Yes, Cancel Transaction</button>
            </div>
        </div>
    </div>
</div>

<?php
function humanTime($date)
{
    if (empty($date)) {
        return '';
    }
    $dateTime = \DateTime::createFromFormat('Y-m-d H:i:s', $date);
    if (empty($dateTime)) {
        return '';
    }
    return $dateTime->format('d/m/Y H:i');
}
