<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Search and Sort Table</title>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"  crossorigin="anonymous"></script>
    <link href="https://cdn.datatables.net/v/bs5/jq-3.6.0/dt-1.13.4/datatables.min.css" rel="stylesheet"/>
    <script src="https://cdn.datatables.net/v/bs5/jq-3.6.0/dt-1.13.4/datatables.min.js"></script>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/gh/xcash/bootstrap-autocomplete@v2.3.7/dist/latest/bootstrap-autocomplete.min.js"></script>


</head>

<script>
    $( document ).ready(function() {
        $('.basicAutoSelect').autoComplete();
        $('#results-table').DataTable({
            processing: true,
            serverSide: true,
            ajax: '/medai?'+ $('#search-form').serialize(),
        });
    });

</script>
<body>
<?php
$now = new \DateTime();
$startTime = clone($now);
$startTime->sub(new \DateInterval('P7D'));
?>
<div class="container mt-3 border rounded mt-2 p-3">
    <form id="search-form">
        <div class="row mb-3">
            <div class="col-md-2">
                <label for="pov_date" class="form-label">Point of View:</label>
                <input type="date" name="pov_date" value="<?=$now->format('Y-m-d');?>" class="form-control">

            </div>
            <div class="col-md-2">
                <label for="pov_hour" class="form-label">&nbsp;</label>
                <input type="time" name="pov_hour" value="<?=$now->format('H:i');?>"  class="form-control">
            </div>

            <div class="col-md-4">
                <label for="client" class="form-label">Client:</label>
                <select id="client" class="form-control basicAutoSelect" name="client_id" placeholder="type to search..."
                        data-url="autocomplete/clients" autocomplete="off"></select>

            </div>
            <div class="col-md-4">
                <label for="loinc" class="form-label">LOINC Code:</label>
                <select id="loinc" class="form-control basicAutoSelect" name="loinc" placeholder="type to search..."
                        data-url="autocomplete/loinc" autocomplete="off"></select>

            </div>

        </div>
        <div class="row mb-3">
            <div class="col-md-2">
                <label for="from_date" class="form-label">From:</label>
                <input type="date" name="from_date"  value="<?=$startTime->format('Y-m-d');?>"  class="form-control">
            </div>
            <div class="col-md-2">
                <label for="from_hour" class="form-label">&nbsp;</label>
                <input type="time" name="from_hour" value="00:00" class="form-control">
            </div>
            <div class="col-md-4">
            </div>
            <div class="col-md-2">
                <label for="to_date" class="form-label">To</label>
                <input type="date" name="to_date" value="<?=$now->format('Y-m-d');?>" class="form-control">
            </div>
            <div class="col-md-2">
                <label for="to_hour" class="form-label">&nbsp;</label>
                <input type="time" name="to_hour" value="<?=$now->format('H:i');?>"  class="form-control">
            </div>
        </div>
        <div class="row mb-3">

        </div>
        <button type="submit" class="btn btn-primary">Search</button>
    </form>
</div>
<div class="container mt-3">
    <table class="table table-striped sortable" id="results-table">
        <thead>
        <tr>
            <th data-defaultsort="asc">First Name</th>
            <th>Last Name</th>
            <th>Concept Name</th>
            <th>LOINC CODE</th>
            <th>Value</th>
            <th>Valid Start Time</th>
            <th>Valid Stop Time</th>
            <th>Transaction Time</th>
        </tr>
        </thead>


    </table>
</div>
<script src="https://cdnjs.cloudflare.com/ajax/libs/sortable/0.8.0/js/sortable.min.js" integrity="sha512-O/Ss2s1nbxIy+oKPr8aGm35Pq3ZKX0OTJ70c8R+6SgS6yPp6UwJ6k25NxDdNz+URZCJN+eT8/ACtxc1sFJyBgA==" crossorigin="anonymous


